services:
  rest-api-java:
    container_name: "token"
    image: postgres:17-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: jwt
      POSTGRES_USER: jwt
      POSTGRES_DB: jwt