spring:
  application:
    name: token

  datasource:
    url: "jdbc:postgresql://localhost:5432/token"
    username: "token"
    password: "token"
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

