spring:
  application:
    name: token

  datasource:
    url: "jdbc:postgresql://localhost:5432/jwt"
    username: "jwt"
    password: "jwt"
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

