spring:
  application:
    name: token

  datasource:
    url: "jdbc:postgresql://127.0.0.1:5433/token"
    username: "token"
    password: "token"
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: always

